# Usa Node.js como base para el entorno de desarrollo
FROM node:20

# Establece el directorio de trabajo
WORKDIR /app/frontend

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Exposición de puertos del contenedor de desarrollo
EXPOSE 4200

# Comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "start"] 