version: '3.8'

services:
  frontend:
    build:
      context: . # Apunta a la raíz del proyecto
      dockerfile: Dockerfile.frontend # Usa el Dockerfile específico para el frontend
    ports:
      - '4005:10000' # Mapea el puerto 10000 del contenedor al puerto 4005 de tu máquina local
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app/frontend:delegated # Monta el directorio del frontend para desarrollo en tiempo real

  backend:
    build:
      context: . # Apunta a la raíz del proyecto
      dockerfile: Dockerfile.backend # Usa el Dockerfile específico para el backend
    ports:
      - '4004:8000' # Mapea el puerto 8000 del contenedor al puerto 4004 de tu máquina local
    environment:
      ORIGINS: 'http://localhost:4005'
    volumes:
      - ./backend:/usr/src/app/backend:delegated # Monta el directorio del backend para desarrollo en tiempo real
      - ./backend/db.sqlite:/usr/src/app/db.sqlite # Monta el archivo de la base de datos SQLite
      - ./backend/db.sqlite-shm:/usr/src/app/db.sqlite-shm # Opcionalmente monta el archivo shm
      - ./backend/db.sqlite-wal:/usr/src/app/db.sqlite-wal # Opcionalmente monta el archivo wal
      - ~/.ssh:/root/.ssh:ro # Configuración SSH
      - ~/.vscode:/root/.vscode:ro # Configuración de VSCode
