version: '3.9'

services:
  # Servicio principal de desarrollo que montará la raíz del proyecto
  devcontainer:
    build:
      context: .  # Contexto para la construcción de la imagen
      dockerfile: Dockerfile  # Archivo Docker para este servicio
    volumes:
      - .:/app  # Monta el directorio actual
      - ~/.ssh:/root/.ssh:ro  # Monta las claves SSH en modo lectura
      - ~/.vscode:/root/.vscode:ro  # Monta la configuración de VSCode en modo lectura

  # Servicio de frontend para producción
  frontend:
    build:
      context: ./frontend  # Contexto para la construcción de la imagen del frontend
      dockerfile: Dockerfile.develop  # Archivo Docker para el frontend
    ports:
      - '4005:80'  # Expone el puerto 80 del contenedor en el puerto 4005 del host
    volumes:
      - ./frontend:/app/frontend:delegated  # Asegúrate de que esté apuntando a la ruta correcta
    command: ['npm','run','start']

  # Servicio de backend para producción
  backend:
    build:
      context: ./backend  # Contexto para la construcción de la imagen del backend
      dockerfile: Dockerfile  # Archivo Docker para el backend
    ports:
      - '4004:8000'  # Expone el puerto 8000 del contenedor en el puerto 4004 del host
    environment:
      ORIGINS: 'http://localhost:4005'  # Variable de entorno para orígenes permitidos
    volumes:
      - ./backend:/app/backend:delegated  # Monta el backend
      - ./backend/db.sqlite:/app/backend/db.sqlite  # Monta la base de datos SQLite
    command: ['npm','run', 'dev']
